name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test-linux:
    name: Test Linux
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        images:
          - swift:5.6-focal
          - swift:5.6-bionic
          - swift:5.6-centos7
          - swift:5.6-amazonlinux2
          - swiftlang/swift:nightly-main
    container: ${{ matrix.images }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cache Swift PM
        uses: actions/cache@v2
        with:
          path: .build
          key: ${{ runner.os }}-${{ matrix.images }}-spm-${{ hashFiles('**/Package.resolved') }}-v2
          restore-keys: ${{ runner.os }}-${{ matrix.images }}-spm-
      - name: Resolve Swift dependencies
        run: swift package resolve
      - name: Build & Test
        run: swift test --enable-test-discovery --parallel --sanitize=thread
