name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test-linux:
    name: Test Linux
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        images:
          - swift:5.3
          - swift:5.4
          - swift:5.5
          - swift:5.6
          - swiftlang/swift:nightly-main
    container: ${{ matrix.images }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cache Swift PM
        uses: actions/cache@v2
        with:
          path: .build
          key: ${{ runner.os }}-${{ matrix.images }}-spm-${{ hashFiles('**/Package.resolved') }}-v2
          restore-keys: ${{ runner.os }}-${{ matrix.images }}-spm-
      - name: Resolve Swift dependencies
        run: swift package resolve
      - name: Build & Test
        run: swift test --enable-test-discovery --parallel

  test-macos:
    name: Test macOS
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        xcode:
          - latest
          - latest-stable
    steps:
      - name: Select toolchain
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: ${{ matrix.xcode }}
      - name: Check out Vapor
        uses: actions/checkout@v3
      - name: Cache Swift PM
        uses: actions/cache@v2
        with:
          path: .build
          key: ${{ runner.os }}-${{ matrix.xcode }}-spm-${{ hashFiles('**/Package.resolved') }}-v2
          restore-keys: ${{ runner.os }}-${{ matrix.xcode }}-spm-
      - name: Resolve Swift dependencies
        run: swift package resolve
      - name: Build & Test
        run: swift test --enable-test-discovery --parallel
